### ISSUE TITLE
plugin.yml is missing from JAR file.

### ISSUE THREAD

**Issue by bbayu123** [HurricanKai/Blacksmith#16]
I decided to open a new issue instead of commenting in #10 cuz it was too old, and I'm not sure if #13 is going to be merged or not, so here I am.

plugin.yml is completely missing from the JAR file, checked builds 136, 138 - 140, all of them didn't have the plugin.yml file inside, it absolutely doesn't exist in the JAR file.
```
[01:07:41] [Server thread/ERROR]: Could not load 'plugins\Blacksmith.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more
```
![image](https://user-images.githubusercontent.com/26726381/41928543-2e030658-79a8-11e8-8ff7-7814ffd1a4db.png)

**Comment by MaxDragonard** [comment]
Same issue. Same error messages. Can't see a plugin.yml in the jar file.

**Comment by UlrichBR** [comment]
I also get the same error message

**Comment by mart-r** [comment]
You can just get the plugin.yml from this here repository and add it to the jar. That's what I did.

Not ideal for a production version of a plugin, but a workaround.
